{% set name = "micropipenv" %}
{% set version = "1.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/micropipenv-{{ version }}.tar.gz
  sha256: 86c96aa2a0f57ba79e51ddea53d20e2e07b8f9dee4c9fa93867e099d25dcf59a

build:
  entry_points:
    - micropipenv = micropipenv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=56.0.0
  run:
    - pip >=9
    - python >=3.6

test:
  imports:
    - micropipenv
  commands:
    - pip check
    - micropipenv --help
  requires:
    - pip

about:
  home: https://github.com/thoth-station/micropipenv
  summary: A simple wrapper around pip to support requirements.txt, Pipenv and Poetry files for containerized applications
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
