{% set name = "micropipenv" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/micropipenv-{{ version }}.tar.gz
  sha256: 6d0cfe4d62bc373f06e67106fc36416b452ae0281fd291151e35f2cc8e16d325

build:
  entry_points:
    - micropipenv = micropipenv:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=56.0.0
  run:
    - pip >=9
    - python >=3.6

test:
  imports:
    - micropipenv
  commands:
    - pip check
    - micropipenv --help
  requires:
    - pip

about:
  home: https://github.com/thoth-station/micropipenv
  summary: A simple wrapper around pip to support requirements.txt, Pipenv and Poetry files for containerized applications
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
